<div align="center"><span class="titlesubsie">LPBB SMA 3 SEMARANG 2011</span></div><br />
          <br />	
        <div style="overflow:auto; height:500px; width: 505px"><p class="no_marg s1" style="width:475px">
        <img src="http://farm6.static.flickr.com/5143/5612318709_73544dd7c4.jpg" class="img-subsie" width="350px"/><br /><br />
	Semarang - 23 Januari 2011 lalu, Pasukan Pengibar Bendera SMA Negeri 3 Semarang telah sukses mengadakan Lomba Peraturan Baris – Berbaris (LPBB) tk. SMA / SMK se- Jateng/DIY dan SMP/MTs se-Kota Semarang.<br />
	Ketua Panitia LPBB, Demy Mukti Setyawan mengatakan, "Lomba ini diselenggarakan untuk memperingati HUT ke-133 SMA 3 Semarang yang diikuti oleh 25 pleton SMA/SMK dan 5 pleton SMP yang masing – masing terdiri dari 17 pasukan, 1 danton dan 2 official. Selain itu, LPBB ini juga bermaksud untuk menumbuhkan rasa nasionalisme, dapat menggalang persatuan dan kesatuan , menciptakan suasana persahabatan, persaudaraan di kalangan pemuda Jawa Tengah dan juga meningkatkan estistensi PASKIBAR SMA Negeri 3 Semarang.<br />
	"LPBB 2011 ini mengangkat tema "Spirit of Java" yang bertujuan untuk meningkatkan sikap dan apresiasi kita terhadap budaya jawa yang semakin hilang di kalangan pemuda. Di dalam lomba ini banyak hal yang menarik dan pastinya belum ada di lomba PBB mana pun, salah satunya adalah tema Jawa yang diaplikasikan di PBB. Sangat menarik perhatian memang, karena tiap pleton diwajibkan menampilkan kreasi yang berhubungan dengan jawa pada gerakan variasi dan formasi. Ada yang menggunakan yel – yel jawa,menyanyi atau bahkan menari jawa," tandasnya.<br />
    Di awali dengan upacara pembukaan di halaman SMA 3  jl .Pemuda 149 yang dibuka oleh wakil dari Gubernur Jawa Tengah, dilanjutkan dengan opening performance oleh GGC Thunders Cheerleaders SMA 3 Semarang dan dilanjutkan dengan perlombaan. Yang menarik lagi, di adakan bazar stand yang menjual macam –macam makanan, minuman, pernak – pernik dan sourvenir. Ada lagi inovasi dari Panitia yg berjumlah 60 orang ini, adalah sistem pemberian materi aba – aba gerakan berjalan yang diberikan kepada peserta 90menit sebelum mereka tampil.<br />
    "Tujuannya untuk mengetes dan mengasah kemampuan Komandan Pleton lebih dari lomba yang biasanya. Selain itu, aspek kekompakan, kerapihan, kebersamaan, keindahan dan kedisiplinan juga menjadi penilaian oleh 12 tim juri yang terdiri dari Kodim 0733 BS, Denpom, Brimob, Polrestabes semarang dan alumni PASKIBAR. Lomba ini terbagi dalam 4 pos, pos kerapihan, gerakan ditempat,gerakan berjalan dan variasi- formasi," tambah si Demy.<br />
    Setelah selesai perlombaan, para peserta juga dihibur oleh MC yang ngebagiin merchendise dan games seru. Ada juga performer dari anak SMA 3 sendiri. Mereka menampilkan kesenian berupa Teatrikal Jawa, Modern Dance oleh TBC Crew dan ALLsize Band. <br />
    Juara Umum tk. SMA mendapatkan piala bergilir dari Dinas Pendidikan Provinsi Jawa Tengah diraih oleh SMK 7 Semarang, juara I – III secara berurutan oleh SMK 7 Semarang, SMA 15 Semarang, SMA 1 Pekalongan. Sementara juara favorit oleh SMA Taruna Nusantara, juara kerapian dan variasi – formasi terbaik di raih oleh SMK 7 Semarang, untuk danton terbaik atas nama Adrianus Rio Eka (SMK 11 Semarang).<br />
    Untuk tingkat SMP, juara umum SMP 5 semarang, juara I-III secara berurutan adalah SMP 5, SMP 2 , SMP 14 Semarang. Juara favorit dan variasi – formasi terbaik di dapat SMP 14 Semarang, sementara danton terbaik diraih oleh Rebina Bilqis A. (SMP 5 Semarang).<br /><br />
<i>Written by : Demy Mukti Setyawan SMA N 3 Semarang</i>



</p></div>