		<div align="center"><span class="titlesubsie">Islamic Festival</span></div><br />	
        <div style="overflow:auto; height:500px; width: 505px"><p class="no_marg s1" style="width:475px">
		Islamic Festival atau sering kami singkat I-Fest adalah festival kebudayaan Islam yang merupakan  program terobosan dari divisi Dakwah ROHIS SMA Negeri 3 Semarang. Kegiatan ini telah diselanggarakan pada hari Minggu tanggal 11 April 2010 di BALAIKOTA Semarang, Jl. Pemuda. <br /><br />
Bentuk kegiatan dalam Islamic Fetival berupa kompetisi kebudayaan Islam, seperti Lomba Rebana, Nasyid, Cerpen,dan Puisi tingkat SMA sederajat se-kota Semarang. I- Fest yang bertemakan Finding NEMO (New Muslim Motivation) ini bertujuan  meningkatkan kreativitas para pemuda dan pemudi Islam, mempererat ukhuwah islamiyah antar siswa muslim SMA se-kota Semarang, dan menimbulkan semangat dakwah pemuda dan pemudi Islam. Dengan maksud dan tujuan yang baik tersebut, kegiatan ini telah mendapat respon yang positif dan dukungan penuh dari berbagai pihak karena SMA Negeri 3 Semarang adalah sekolah negeri pertama yang pernah mengadakan kegiatan kompetisi untuk sekolah-sekolah SMA sederajat se-kota Semarang. <br /><br />
Awalnya memang tidak mudah dalam mempersiapkan acara ini. Berbagai hambatan, masalah, dan  rinatangan selalu dating bertubi-tubi. Dari masalah dana, tempat dan waktu, serta pro dan kontra antar panitia dan peserta. Namun dengan tekad, usaha, kerja sama, dan ikhtiar para siswa-siswi ROHIS SMA N 3 Semarang, I-Fest ini alhamdulillah dapat berjalan dengan lancar. Tentu saja berkat rahmat ALLAH SWT yang telah memberi kemudahan bagi para hamba-Nya untuk menyelenggarakan kegiatan di jalan Allah.  <br /><br />
Alhamdulillah, I-Fest telah terlaksana tanpa hambatan. Waktu acaranya tidak molor, tepat sesuai rencana dalam rundown. Pesertanya pun tertib, sehingga memudahkan panitia. Dari panggung utama yang dibawakan oleh kedua MC kami yaitu Karuniawan dan Prima secara komunikatif dan menarik, sehingga lomba rebana dan nasyid berjalan dengan lancar sesuai urutan. Hingga di panggung kedua, yaitu lomba puisi yang pesertanya paling banyak pun derjalan dengan baik.  <br /><br />
Acara I-Fest ini tidak hanya diramaikan oleh peserta lomba, namun juga ada stand-stand, seperti stand sponsor, stand makanan dan minuman, serta stand subsie-subsie SMA N 3 Semarang, yaitu MOCHI (subsie Bahasa Jepang), KPSKAPA, Kop Soeringgit, SISTRA(sekarang apa ya??Lupa), ROHIS sendiri, dan lain sebagainya. Tak lupa, acara ini juga dibuka untuk umum, baik yang tidak mengikuti lomba boleh hadir dan meramaikan I-Fest ini. <br /><br />
Yang paling menarik dan dinanti-nanti oleh para peserta dan pengunjung adalah bintang tamu yang kami hadirkan dalam I-Fest ini, yaitu AWAN Nasyid. AWAN Nasyid menjadi favorit bintang tamu bagi ROHIS SMA Negeri 3 Semarang karena sering kalinya diundang dalam kegiatan keagamaan kami. AWAN Nasyid memang telah berprestasi menjadi juara Nasional dalam Lomba Nasyid. Sehingga salah satu personilnya patut kami jadikan dewan juri untuk lomba nasyid yang kami selenggarakan dalam acara kami. <br /><br />
AWAN Nasyid tampil sebelum hasil lomba diumumkan. Peserta tetap setia menanti meski hujan telah turun, dan acaranya pun tidak terhambat hanya karena hal itu. Semua tetap berjalan dengan lancar hingga penutupan acara oleh Bapak M.S. Anwari s.ag.,selaku Pembina ROHIS SMA Negeri 3 Semarang.


</p></div>