<div align="center"><span class="titlesubsie2">GAPUTA GO GREEN</span></div><br />
          <br />	
        <div style="overflow:auto; height:500px; width: 505px"><p class="no_marg s1" style="width:475px">
		<img src="http://farm5.static.flickr.com/4141/4803487963_faccef0e5f.jpg" class="img-subsie"/><br /><br />
		Organisasi Pecinta Alam SMA N  3 Semarang (Gaputa) yang pada tahun 2009 telah mengadakan kegiatan penanaman mangrove  bertema Mangrove For Life, di tahun 2010 ini kembali mengadakan sebuah kegiatan peduli lingkungan yang bernama Gaputa Go Green. Kegiatan tersebut dilaksanakan 24-25 April 2010 di Bumi Perkemahan Gogik, Ungaran.Kegiatan ini melibatkan  pelajar SMP/SMA/SMK se-Kota Semarang. Dalam kegiatan ini para peserta diajak untuk lebih peduli terhadap lingkungan. Hal itu diwujudkan dalam aktivitas-aktivitas yang dilaksanakan dalam acara Gaputa Go Green.  Dalam kegiatan yang berlangsung selama 2 hari tersebut , peserta diajak untuk mendaur ulang kertas, membuat pupuk organik,menanam pohon,pengamatan bintang dan pasti nya ada outbound juga. <br /><br />
Pada hari sabtu, 24 April 2010 para peserta diwajibkan kumpul jam 7 pagi di SMA 3, namun saking antusiasnya mereka, banyak juga lho yang sudah datang dari jam 6.30. Acara  dimulai  hari sabtu jam 8 pagi dengan upacara pelepasan dari bapak kepala SMA N 3 Semarang, yaitu Bapak Drs. Hari Waluyo, M.M. didampingi oleh Ibu Mamik Lis selaku wakasek bidang kesiswaan, serta Bapak Djumasri selaku Pembina Gaputa. Upacara pelepasan pada pagi itu berlangsung khidmat dan para peserta tampak sangat memperhatikan nasihat-nasihat dari bapak kepala sekolah. Sebelum keberangkatan para peserta yang sudah dibagi dalam 9 kelompok tersebut diwajibkan untuk membuat yel-yel yang nantinya akan mereka tampilkan dalam sesi tertentu di Gaputa GoGreen. Dalam waktu yang relative singkat, masing-masing kelompok mampu membuat yel-yel yang sangat bagus. Padahal asal tahu saja, mereka yang ada dalam kelompok itu berasal dari sekolah yang berbeda-beda lho. Dan mereka juga baru dipertemukan saat di acara ini. Hebat kan ! Tepat  jam 9 pagi, seluruh peserta meninggalkan SMA 3 untuk menuju Bumi Perkemahan Gogik, Ungaran. <br /><br />    
 	Begitu sampai di kawasan Ungaran, kami disambut dengan hujan yang cukup deras. Awalnya kami sempat khawatir juga, sebab semua kegiatan di Gaputa Go Green ini kan outdoor, jadi kalau hujan kan gak asyik. Tapi, sepertinya alam memang mengerti niat baik kita. Tak lama setelah seluruh peserta tiba di Buper, hujan reda dan berganti dengan matahari yang cerah. Tanpa menunggu lama (takut hujan lagi) acara langsung dibuka oleh Bapak Djumasri selaku Pembina Gaputa dan sekaligus sebagai wakil dari pihak sekolah. Kegiatan pertama dimulai dengan daur ulang kertas. Dalam acara ini masing-masing kelompok diberi 1 set perlengkapan daur ulang (bubur kertas,screen,kain,petunjuk daur ulang). Pada awalnya mereka diberi pengarahan serta diperlihatkan proses pembuatannya oelh pembicara dalam sesi ini yaitu Mas Nugroho, dkk dari Undip. Tapi, memang ya para peserta ini aktif sekali, belum selesai penjelasan dari Mas Nugroho mereka sudah langsung mencobanya. Kalau ditanya hasilnya, bagus kok, enggak kalah sama buatan instrukturnya. <br /><br />
Acara selanjutnya yaitu pembuatan pupuk organic. Dalam sesi ini dipandu oleh pembicara dari Tim Teknologi Tepat Guna Tunggul Sakti yaitu Bapak Heri Gea. Dalam kegiatan ini, penduduk setempat juga dilibatkan untuk menyaksikan cara pengolahannya Jadi, banyak banget kan manfaat positif  dari acara ini dan manfaat  itu enggak cuma buat peserta Gaputa Go Green aja melainkan untuk masyarakat juga . Sore harinya seluruh peserta diajak untuk menanam bibit pohon di lahan kritis di sekitar lokasi perkemahan.  Setelah semua kegiatan tadi, malam harinya mereka diajak refreshing sedikit dengan menonton film bersama, namun tetap bertemakan lingkungan. Larut malamnya, peserta diajak untuk pengamatan gugus bintang dan bulan menggunakan teropong bintang. Jarang-jarang lho bisa mengamati benda-benda langit menggunakan teropong bintang. Di Hari Minggu para peserta diajak untuk menikmati keindahan alam sekaligus outbound. Dalam outbound, mereka bisa merasakan berbagai permainan outbound yang seru, contohnya rigging, log line, green tower, treasure  island, dan masih banyak lagi yang seru-seru. Jadi, gak rugi deh kalau kamu mau gabung dalam kegiatan yang diadakan oleh Gaputa.  Buat yang belum ikutan, gak usah kuatir, karena kami akan terus mengadakan kegiatan yang positif buat lingkungan. Nantikan acara kami selanjutnya ya ! Dapss 



</p></div>