<div align="center"><span class="titlesubsie">GEBYAR GANESHA</span></div><br />
          <br />	
        <div style="overflow:auto; height:500px; width: 505px"><p class="no_marg s1" style="width:475px">
		Gebyar  Ganesha merupakan salah satu kegiatan dalam proker subsie Patroli Keamanan Sekolah SMA Negeri 3 Semarang yang rutin diadakan setiap tahun. Kegiatan ini berupa lomba yang awalnya hanya ditujukan untuk tingkat SMA dengan jenis lomba yang juga merupakn materi dari ekskul PKS itu sendiri yaitu: PBB, senam PKS, Gatur Lantas dan Pentas Seni. Untuk lomba PBB, senam PKS, dan Gatur Lantas yang di lakukan di lapangn kami bekerjasama dengan pihak Polwiltabes Semarang untuk menjadi juri.  Kegiatan ini bertujuan untuk menjalin silaturahmi dengan anggota PKS dari sekolah lain terutama daerah Jawa Tengah dan sekitarnya.<br />
	Tahun ini pun PKS SMA Negeri 3 Semarang kembali mengadakan lomba Gebyar Ganesha yang telah usai pada hari Minggu 28 Februari 2010 lalu. Ada sedikit perbedaan pada Gebyar Ganesha tahun ini dengan tahun – tahun sebelumnya. Di tahun ini, Gebyar Ganesha member kesempatan pada siswa – siswi SMP di Kota Semarang untuk turut berpartisipasi dalam kegiatan tahunan ini. Jenis lomba untuk tingkat SMP pun tidak sama dengan jenis lomba tingkat SMA, untuk SMP lebih difokuskan pada pengetahuan umum dan kelalulintasan dengan jenis lomba pentas seni, lomba debat, cerdas cermat, dan mading. Tidak hanya itu, tahun ini untuk SMA juga ada satu jenis lomba tambahan yaitu ketabgkasan. Dalam lomba ketangkasan  ini peserta diharuskan melewati rintangan dan palang dengan menggunakan sepeda motor yang telah disediakan oleh panitia, kami bekerja sama dengan pihak motor Honda selama mempersiapkan lomba tambahan ini. <br />
	Peserta lomba Gebyar Ganesha tahun ini didominasi oleh siswa SMP yang bejumlah tak kurang dari 108 siswa. Sedangkan untuk SMA sekitar 76 siswa. Pemenang lomba SMA untuk kategori PBB juara 1 diraih oleh SMA N 1 Cepiring, juara 2 diraih oleh SMK Taman Siswa Sukoharjo, dan juara 3 diraih oleh SMA Kartika III – 1 Banyubiru. Kategori Gaturlantas jura 1 dimenangkan oleh SMK Taman Siswa Sukoharjo, juara 2 oleh SMA N 1 Cepiring, dan juara 3 diraih oleh SMA N1 Demak. Untuk ketregori Senam juara 1 kembali diraih oleh SMK Taman Siswa Sukoharjo, untuk juara 2 oleh SMA N 1Cepiring, dan juara 3 SMA N 1 Demak. Kategoei Pentas Seni juara 1 diraih olehSMK Taman Siswa Sukoharjo, juara 2 SMA N 1 Demak dan juara 3 SMA N 1 Cepiring. Kategori Ketangkasan diwakili oleh dua peserta dari tiap sekolah, juara 1 diraih oleh SMA N 1 Cepiring atas nama Rio Adi, juara 2 diraih oleh SMA N 1 Demak atas nama Supriyanto, juara 3 diraih oleh Ardi Setiyandi dari SMA N 1 Cepiring. Sedangkan untuk lomba SMP kategori cerdas cermat juara 1 dimenangkan oleh SMP Kesatrian 2, juara 2 diraih oleh SMPIT Harapan Bunda dan juara 3 diraih oleh SMP N 5 Semarang. Untuk kategori pentas seni juara 1 dimenangkan oleh SMP N 23 Semarang, juara 2 dimenangkan oleh SMP Kesatrian 2, juara 3 diraih oleh SMP N 5 Semarang. Ketegori lomba debat juara 1 diraih oleh SMP Nasima, juara 2 diraih oleh SMP Kristen Tri Tunggal, juara 3 diraih oleh SMP Kesatrian 2. Kategori lomba madding juara 1 diraih oleh SMP Nasima, juara 2 diraih oleh SMPIT Harapan Bunda, juara 3 diraih oleh SMP N 5 Semarang. Berdasarkan hail akumulasi keseluruhan nilai lomba uara umum tahun ini untuk SMA diraih oleh SMK Taman Siswa Sukoharjo, hal ini cukup menjadi perhatian baik peserta maupun panitia karena seluruh anggotanya terdiri dari pelajar putri. Sedangkan juara umum SMP diraih oleh SMP Kesatrian 2.
	



</p></div>